# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e435e2383bbdab272a31933199f273f4"
name = "selfhostedapp1"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[app_proxy]
url = "https://example.com/larapush"
subpath = "larapush"
prefix = "apps"
